# docker-compose.yml
services:
  mail-postfix:
    build:
      context: .
      dockerfile: postfix.Dockerfile
    container_name: mail-postfix
    hostname: mail.local
    networks:
      - smtp-net
    dns:
      - 172.28.0.253
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./configs/postfix:/postfix
      - ./scripts:/scripts
      - ./artifacts:/artifacts

  dns-dnsmasq:
    image: andyshinn/dnsmasq     # DNSMasq 공식 이미지
    container_name: dns-dnsmasq
    platform: linux/amd64
    command: ["-k"]              # 포그라운드 모드
    networks:
      smtp-net: # smtp-net에 고정 IP 할당
        ipv4_address: 172.28.0.253
    ports:
      - "53:53/udp"              # DNS

  mua-debian:
    container_name: mua-debian
    build:
      context: .
      dockerfile: mua.Dockerfile
    networks:
      - smtp-net
    dns:
      - 172.28.0.253 # dns-dnsmasq의 고정 IP로 변경
    volumes:
      - ./scripts:/scripts
      - ./artifacts:/artifacts
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 3s

  controller:
    build: ./controller
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: controller
    networks:
      - default
      - smtp-net
    dns:
      - 172.28.0.253
    volumes:
      - ./scripts:/scripts
      - ./artifacts:/artifacts
      - ./configs/postfix:/shared/postfix # 호스트 설정 바인드
    tty: true
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s  # 60초에서 5초로 줄임
      timeout: 5s
      retries: 2
      start_period: 3s  # 시작 후 초기 대기 시간 추가

networks:
  smtp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
  dns-net:
    driver: bridge
  mgmt-net:
    driver: bridge
