# docker-compose.yml
services:
  mail-postfix:
    image: boky/postfix          
    container_name: mail-postfix
    environment:
      - ALLOW_EMPTY_SENDER_DOMAINS=yes
      - SMTP_SERVER_HOSTNAME=mail.local
    networks:
      - smtp-net
    ports:
      - "25:25"                  # SMTP Relay
      - "587:587"                # Submission
    volumes:
      - postfix-config:/etc/postfix

  dns-dnsmasq:
    image: andyshinn/dnsmasq     # DNSMasq 공식 이미지
    container_name: dns-dnsmasq
    platform: linux/amd64
    command: ["-k"]              # 포그라운드 모드
    ports:
      - "53:53/udp"              # DNS

  mua-debian:
    container_name: mua-debian
    build:
      context: .
      dockerfile: mua.Dockerfile
    networks:
      - smtp-net
    volumes:
      - ./scripts:/scripts
      - ./artifacts:/artifacts
    tty: true
    stdin_open: true

  controller:
    build: ./controller
    cap_add:
      - NET_ADMIN
      - NET_RAW
    container_name: controller
    networks:
      - default
      - smtp-net
    volumes:
      - ./scripts:/scripts
      - ./artifacts:/artifacts
      - postfix-config:/shared/postfix
    tty: true

networks:
  smtp-net:
    driver: bridge
  dns-net:
    driver: bridge
  mgmt-net:
    driver: bridge

volumes:
  postfix-config:
